left = (
    "Army",
    "North Carolina",
    "Michigan State",
    "Kansas",
    "Oregon",
    "Missouri",
    "Clemson",
    "Ohio State",
    "Notre Dame",
    "Southern California",
    "Miami",
    "Tennesee",
    "Houston",
    "Washington",
    "Buffalo",
    "Chicago",
    "Cincinnati",
    "Detroit",
    "Cleveland",
    "L.A. Rams",
    "San Fancisco",
    "Green Bay",
    "Dallas",
)

right = (
    "Buffalo",
    "Lousiville",
    "Western Michigan",
    "Central Michigan",
    "Nebraska",
    "South Carolina",
    "Auburn",
    "Oklahoma",
    "Georgia",
    "Stanford",
    "Tampa Bay",
    "Oakland",
    "Jacksonville",
    "Philidelphia",
    "N.Y. Jets",
    "Atlanta",
    "Baltimore",
    "Arizona",
    "Pittsburgh",
    "Indianapolis",
    "Carolina",
    "Seattle",
    "N.Y. Giants",
)